apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kac
subjects:
- kind: ServiceAccount
  name: kac
  namespace: example
