apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: default
  labels:
    name: nginx
spec:
  imagePullSecrets:
    - name: test-credentials
  containers:
    - name: nginx
      image: nginx