name: publish

on:
  push:
    branches:
      - master
      - main
      - legacy/*
  pull_request:
    types:
      - opened
      - synchronize
      - closed
    branches:
      - master
      - main
      - legacy/*

jobs:
  
  code_testing:
    uses: ptonini/gha-workflows/.github/workflows/code-testing.yaml@main
    if: github.event.action != 'closed' && github.event.head_commit.author.name != 'github-actions[bot]' && !contains(github.event.repository.topics, 'skip-testing')
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  code_linting:
    uses: ptonini/gha-workflows/.github/workflows/code-linting.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action) && !contains(github.event.repository.topics, 'skip-linting')
  security_scan:
    uses: ptonini/gha-workflows/.github/workflows/trufflehog.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
  release_please:
    uses: ptonini/gha-workflows/.github/workflows/release-please.yaml@main
    if: github.event_name == 'push'
  
  startup:
    uses: ptonini/gha-workflows/.github/workflows/startup.yaml@main
    if: (!contains(github.event.pull_request.head.ref, 'release-please--'))
  
  build_candidate:
    uses: ptonini/gha-workflows/.github/workflows/publish-docker-image.yaml@main
    if: github.event_name == 'pull_request' && contains('opened synchronize', github.event.action)
    needs:
      - startup
    with:
      repository: ${{ needs.startup.outputs.docker_repository }}
      tags: ${{ format('latest pr{0}', github.event.number) }}
    secrets:
      BUILD_ARGUMENTS: --build-arg BUILD_USERNAME=${{ github.actor }} --build-arg BUILD_PASSWORD=${{ secrets.GH_PACKAGES_TOKEN }}
  
  approve_candidate:
    uses: ptonini/gha-workflows/.github/workflows/retag-docker-image.yaml@main
    if: github.event.pull_request.merged
    needs:
      - startup
    with:
      source_tag: ${{ format('pr{0}', github.event.pull_request.number) }}
      tag: pr-approved
  
  promote_candidate:
    uses: ptonini/gha-workflows/.github/workflows/retag-docker-image.yaml@main
    if: github.event_name == 'push' && github.event.head_commit.author.name == 'github-actions[bot]'
    needs:
      - startup
    with:
      source_tag: pr-approved
      tag: ${{ needs.startup.outputs.release_version }}